#!/bin/bash
local_config_dir="$(dirname "$(readlink -f "$0")")"
source "${local_config_dir}/docker.config"

if [ $# -eq 2 ]
then
	container="$1"
	executable="$2"
else
	container="$1"
	executable="${container}"
fi

if [ -d "${local_docker_home}/${local_docker_repo}/${container}" ]
then
	echo "Error: '${local_docker_home}/${local_docker_repo}/${container}' already exists, aborting."
	exit 1
fi

if [ -e "${local_bin_dir}/${executable}" ]
then
	echo "Error: '${local_bin_dir}/${executable}' already exists, aborting."
	exit 1
fi

mkdir -p "${local_docker_home}/${local_docker_repo}/${container}"
(
	cd "${local_docker_home}/${local_docker_repo}/${container}" || exit
	make_dockerfile "${executable}"
	docker-build -t "${local_docker_repo}/${container}"
	ln -s "${local_docker_home}/${local_docker_repo}/${container}/launch" "${local_bin_dir}/${executable}"
)

