#!/bin/bash
local_config_dir="$(dirname "$(readlink -f "$0")")"
source "${local_config_dir}/docker.config"

volumeName="compose_$(pwd | md5sum | tr -cd '[:alnum:]')"

function remove_volume() {
	docker-umount "${volumeName}" >> /dev/stderr
}

if type docker-mount &> /dev/null
then
	# We need the volume name to be the same each time, since docker-compose uses it as a label.
	trap "remove_volume" EXIT
	docker-mount "${volumeName}" >> /dev/stderr
	docker.ssh.pipe.cmd bash <<-EOC
		cd "${volumeName}" && docker-compose "$@"
	EOC
else
	docker-compose "$@"
fi
