#!/bin/bash
local_config_dir="$(dirname "$(readlink -f "$0")")"
source "${local_config_dir}/docker.config"

volumeName="$(uuidgen)"

function remove_volume() {
	docker-umount "${volumeName}"
}

if type docker-mount &> /dev/null
then
	trap "remove_volume" EXIT
	docker-mount "${volumeName}"
	docker run --rm -v"${volumeName}":"$(pwd)" -w"$(pwd)" "$@"
else
	docker run --rm -v"$(pwd)":"$(pwd)" -w"$(pwd)" "$@"
fi
