#!/bin/bash
debug () [[ -v DEBUG ]]

debug && set -x
debug && set -o xtrace
debug && set -v

if [ $# -ne 1 ] ; then
	echo Usage: $(basename "$0") volume
	exit 1
fi

mountVolume=$1

dummy=$(docker volume rm "${mountVolume}")

docker.ssh.cmd fusermount -zu "/home/docker/${mountVolume}"
docker.ssh.cmd rmdir "${mountVolume}"

