#!/bin/bash

function remove_volume() {
	volumeName=$1
	docker-umount ${volumeName} >> /dev/stderr
}

if type docker-mount &> /dev/null
then
	# We need the volume name to be the same each time, since docker-compose uses it as a label.
	volumeName="compose_$(pwd | md5sum | tr -cd '[:alnum:]')"
	trap "remove_volume ${volumeName}" EXIT
	docker-mount ${volumeName} >> /dev/stderr
	/usr/bin/ssh docker@docker.local "cd ~/${volumeName} && docker-compose $@"
else
	docker-compose "$@"
fi
