#!/bin/bash

function remove_volume() {
	volumeName=$1
	echo -n Removing volume: >> /dev/stderr
	docker-umount ${volumeName} >> /dev/stderr
}

if type docker-mount &> /dev/null
then
	volumeName=$(uuidgen)
	trap "remove_volume ${volumeName}" EXIT
	echo -n Creating volume: >> /dev/stderr
	docker-mount ${volumeName} >> /dev/stderr
	docker run --rm -v${volumeName}:\"$(pwd)\" -w\"$(pwd)\" "$@"
else
	docker run --rm -v\"$(pwd)\":\"$(pwd)\" -w\"$(pwd)\" "$@"
fi
