#!/bin/bash
debug () [[ -v DEBUG ]]

debug && set -x
debug && set -o xtrace
debug && set -v

if [ $# -ne 1 ] ; then
	echo Usage: $(basename "$0") volume
	exit 1
fi

mountVolume=$1

ip=docker.local

sshCMD() {
	/usr/bin/ssh docker@${ip} "$@"
}

dummy=$(docker volume rm "${mountVolume}")

sshCMD "fusermount -zu /home/docker/${mountVolume}"
sshCMD "rmdir ${mountVolume}"

