#!/bin/bash
local_config_dir="$(dirname "$(readlink -f "$0")")"
source "${local_config_dir}/docker.config"

docker-run -v "${remote_docker_socket}":/var/run/docker.sock -it "${remote_docker_container}" compose "$@"
