#!/bin/bash
debug () [[ -v DEBUG ]]

debug && set -x
debug && set -o xtrace
debug && set -v

function remove_volume() {
	volumeName=$1
	docker-umount ${volumeName}
}

if type docker-mount &> /dev/null
then
	volumeName=$(uuidgen)
	trap "remove_volume ${volumeName}" EXIT
	docker-mount ${volumeName}
	docker run --rm -v${volumeName}:\"$(pwd)\" -w\"$(pwd)\" "$@"
else
	docker run --rm -v\"$(pwd)\":\"$(pwd)\" -w\"$(pwd)\" "$@"
fi
