#!/bin/bash

function remove_volume() {
	volumeName=$1
	docker-umount ${volumeName} >> /dev/stderr
}

if type docker-mount &> /dev/null
then
	volumeName=$(uuidgen)
	trap "remove_volume ${volumeName}" EXIT
	docker-mount "${volumeName}" "/home/onno/.ssh" >> /dev/stderr
fi

docker-run --rm -v${volumeName}:"/home/docker/.ssh" itmaze/git:latest "$@"
